(define (stack-push st val)
  (cons val st)
)
(define (stack-read st)
  (car st)
)
(define (stack-pop st)
  (cdr st)
)
(define (calc-add st)
  (stack-push (stack-pop (stack-pop st)) (+ (stack-read st) (stack-read (stack-pop st))))
)
(define (calc-sub st)
  (stack-push (stack-pop (stack-pop st)) (- (stack-read (stack-pop st)) (stack-read st) ))
)
(define (calc-mul st)
  (stack-push (stack-pop (stack-pop st)) (* (stack-read st) (stack-read (stack-pop st))))
)
